set_device_name:
  fields:
    mac:
      required: true
      example: "3C:A6:F6:00:11:22"
      selector:
        text:
    name:
      required: true
      example: "Drucker Arbeitszimmer"
      selector:
        text:

wake_on_lan:
  fields:
    mac:
      required: true
      example: "3C:A6:F6:00:11:22"
      selector:
        text:

set_device_comment:
  fields:
    mac:
      required: true
      example: "3C:A6:F6:00:11:22"
      selector:
        text:
    comment:
      required: false
      example: "Wohnzimmer"
      selector:
        text:

acknowledge_device:
  fields:
    mac:
      required: true
      example: "3C:A6:F6:00:11:22"
      selector:
        text:

pihole_add_record:
  fields:
    ip:
      required: true
      example: "192.168.9.178"
      selector:
        text:
    dns_names:
      required: true
      example: "mk-esx20.fritz.box"
      selector:
        text:

pihole_update_record:
  fields:
    old_record:
      required: true
      example: "192.168.9.178 mk-esx20.fritz.box"
      selector:
        text:
    ip:
      required: true
      selector:
        text:
    dns_names:
      required: true
      selector:
        text:

pihole_delete_record:
  fields:
    old_record:
      required: true
      example: "192.168.9.178 mk-esx20.fritz.box"
      selector:
        text:

pihole_sync_all:
  name: Alle Geräte mit Pi-hole synchronisieren
  description: Überträgt alle FRITZ!Box-Geräte mit Name und IP-Adresse an Pi-hole.
