set_device_name:
  fields:
    mac:
      required: true
      example: "3C:A6:F6:00:11:22"
      selector:
        text:
    name:
      required: true
      example: "Drucker Arbeitszimmer"
      selector:
        text:

wake_on_lan:
  fields:
    mac:
      required: true
      example: "3C:A6:F6:00:11:22"
      selector:
        text:

set_device_comment:
  fields:
    mac:
      required: true
      example: "3C:A6:F6:00:11:22"
      selector:
        text:
    comment:
      required: false
      example: "Wohnzimmer"
      selector:
        text:

acknowledge_device:
  fields:
    mac:
      required: true
      example: "3C:A6:F6:00:11:22"
      selector:
        text:
